# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-10 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_remove_category_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='categories', to='myblog.Post'),
        ),
    ]
