# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-10 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_category_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
