# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-13 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0016_auto_20190210_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post',
        ),
    ]
